"""Structural type for the data store.

`Store` (filesystem) and `S3Store` both satisfy this protocol implicitly — no
inheritance change needed. Code that touches storage should annotate against
`StoreProtocol`, not the concrete classes, so swapping backends is painless and
mypy stops needing `cast(Store, ...)` lies in the routes.
"""

from __future__ import annotations

from datetime import date
from typing import Any, Protocol

from digest.store import Source


class StoreProtocol(Protocol):
    # ---- layout ----
    def ensure_layout(self) -> None: ...

    # ---- profile ----
    def read_profile(self) -> str: ...
    def write_profile(self, text: str) -> None: ...

    # ---- sources ----
    def list_sources(self) -> list[Source]: ...
    def write_sources(self, sources: list[Source]) -> None: ...

    # ---- digests ----
    def write_digest(self, d: date, items: list[dict[str, Any]], agent_notes: str) -> None: ...
    def rewrite_digest(self, d: date, data: dict[str, Any]) -> None: ...
    def read_digest(self, d: date) -> dict[str, Any] | None: ...
    def list_digests(self) -> list[date]: ...
    def recent_digest_items(self, days: int = 7) -> list[dict[str, str]]: ...
    def update_item_feedback(self, d: date, item_id: str, value: str | None) -> bool: ...

    # ---- feedback ----
    def append_feedback(self, event: dict[str, Any]) -> None: ...
    def read_recent_feedback(self, days: int = 30) -> list[dict[str, Any]]: ...

    # ---- runs ----
    def append_run(self, run: dict[str, Any]) -> None: ...
    def read_recent_runs(self, days: int = 30) -> list[dict[str, Any]]: ...
    def read_run(self, run_id: str) -> dict[str, Any] | None: ...

    # ---- reflection memory ----
    def read_reflection_memory(self) -> str: ...
    def write_reflection_memory(self, text: str) -> None: ...

    # ---- reflection drain coordination ----
    def read_reflection_cursor(self) -> str | None: ...
    def write_reflection_cursor(self, ts: str) -> None: ...
    def try_acquire_reflection_lock(self, *, ttl_seconds: int = 900) -> str | None: ...
    def release_reflection_lock(self, token: str) -> None: ...

    # ---- git (no-op on S3Store) ----
    def git_init_if_needed(self) -> None: ...
    def git_commit_all(self, message: str) -> bool: ...
