/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/digest/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Today
         * @description Most recent digest. May be yesterday's if today's hasn't run yet.
         */
        get: operations["get_today_api_digest_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/digest/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Date */
        get: operations["get_by_date_api_digest__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/digests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Digests
         * @description Archive index: only digests that contain at least one reacted item.
         *     `item_count` reflects reacted items only, since unreacted ones live in the feed.
         */
        get: operations["list_digests_api_digests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feed
         * @description Inbox-style feed: every unreacted item across all digests, newest first.
         *     Once an item is thumbed up/down it leaves the feed and only appears in the archive.
         */
        get: operations["get_feed_api_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Naive substring search across all digests' titles + summaries.
         *     Single-user app, so no need for a real index.
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description All run summaries, newest first (one entry per run). Excludes tool_log.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Full run detail for a specific run_id, including the tool call log.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_runs/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Runs
         * @description Last 14 days of run summaries (curation + reflection), newest first.
         */
        get: operations["recent_runs_api__runs_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Feedback */
        post: operations["post_feedback_api_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Chat */
        post: operations["post_chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Profile Markdown
         * @description Return the current `profile.md` content for the live profile view.
         */
        get: operations["read_profile_markdown_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root Dev */
        get: operations["root_dev__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatFeedback */
        ChatFeedback: {
            /** Text */
            text: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** History */
            history: components["schemas"]["ChatTurn"][];
        };
        /** ChatTurn */
        ChatTurn: {
            /** Role */
            role: string;
            /** Text */
            text: string;
        };
        /** Digest */
        Digest: {
            /** Date */
            date: string;
            /** Generated At */
            generated_at?: string | null;
            /** Items */
            items: components["schemas"]["DigestItem"][];
            /**
             * Agent Notes
             * @default
             */
            agent_notes: string;
            /**
             * Runs
             * @default []
             */
            runs: {
                [key: string]: unknown;
            }[];
        };
        /** DigestItem */
        DigestItem: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Duration Min */
            duration_min?: number | null;
            /** Feedback */
            feedback?: string | null;
            /** Run Id */
            run_id?: string | null;
        };
        /** DigestSummary */
        DigestSummary: {
            /** Date */
            date: string;
            /** Item Count */
            item_count: number;
            /** Has Unread */
            has_unread: boolean;
        };
        /** FeedItem */
        FeedItem: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Duration Min */
            duration_min?: number | null;
            /** Feedback */
            feedback?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Digest Date */
            digest_date: string;
            /** Run Started At */
            run_started_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProfileMarkdown */
        ProfileMarkdown: {
            /** Markdown */
            markdown: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Date */
            date: string;
            /** Run Id */
            run_id?: string | null;
            /**
             * Kind
             * @default curation
             * @enum {string}
             */
            kind: "curation" | "reflection";
            /** Started At */
            started_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Tool Calls */
            tool_calls?: number | null;
            /**
             * Profile Patches
             * @default 0
             */
            profile_patches: number;
            /**
             * Sources Changed
             * @default 0
             */
            sources_changed: number;
            /**
             * Reflection Notes
             * @default
             */
            reflection_notes: string;
            /**
             * Item Count
             * @default 0
             */
            item_count: number | null;
            /** Triggering Feedback */
            triggering_feedback?: {
                [key: string]: unknown;
            } | null;
            /** Exit Reason */
            exit_reason?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Tool Log
             * @default []
             */
            tool_log: components["schemas"]["ToolCallEntry"][];
            /**
             * Agent Notes
             * @default
             */
            agent_notes: string;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["DigestItem"][];
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /**
             * User Prompt
             * @default
             */
            user_prompt: string;
        };
        /** RunSummaryOut */
        RunSummaryOut: {
            /** Date */
            date: string;
            /** Run Id */
            run_id?: string | null;
            /**
             * Kind
             * @default curation
             * @enum {string}
             */
            kind: "curation" | "reflection";
            /** Started At */
            started_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Tool Calls */
            tool_calls?: number | null;
            /**
             * Profile Patches
             * @default 0
             */
            profile_patches: number;
            /**
             * Sources Changed
             * @default 0
             */
            sources_changed: number;
            /**
             * Reflection Notes
             * @default
             */
            reflection_notes: string;
            /**
             * Item Count
             * @default 0
             */
            item_count: number | null;
            /** Triggering Feedback */
            triggering_feedback?: {
                [key: string]: unknown;
            } | null;
            /** Exit Reason */
            exit_reason?: string | null;
            /** Error */
            error?: string | null;
        };
        /** SearchHit */
        SearchHit: {
            /** Date */
            date: string;
            /** Item Id */
            item_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Snippet */
            snippet: string;
        };
        /** ThumbFeedback */
        ThumbFeedback: {
            /** Item Id */
            item_id: string;
            /**
             * Value
             * @enum {string}
             */
            value: "up" | "down" | "none";
            /** Notes */
            notes?: string | null;
        };
        /** ToolCallEntry */
        ToolCallEntry: {
            /** Ts */
            ts: string;
            /** Tool */
            tool: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Outcome */
            outcome: string;
            /** Thinking */
            thinking?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_today_api_digest_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Digest"] | null;
                };
            };
        };
    };
    get_by_date_api_digest__day__get: {
        parameters: {
            query?: {
                feedback_only?: boolean;
            };
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Digest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_digests_api_digests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestSummary"][];
                };
            };
        };
    };
    get_feed_api_feed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedItem"][];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryOut"][];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_runs_api__runs_recent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    post_feedback_api_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThumbFeedback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatFeedback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_markdown_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileMarkdown"];
                };
            };
        };
    };
    chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_dev__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
